name: Deploy a AWS con Terraform

on:
  push:
    branches:
      - main # O la rama principal de tu proyecto

env:
  AWS_REGION: us-east-1 # Debe coincidir con la variable de Terraform
  DOCKER_IMAGE_NAME: ${{ secrets.DOCKER_IMAGE_NAME }}
  IMAGE_TAG: latest

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      # --- Fase 1: Construir y Subir Imagen Docker ---
      - name: Iniciar sesión en Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Construir y etiquetar la imagen Docker
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_IMAGE_NAME }}:${{ env.IMAGE_TAG }}

      # --- Fase 2: Aplicar Terraform (Infraestructura) ---
      - name: Configurar las credenciales de AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Configurar Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0 # Usa una versión compatible

      - name: Inicializar Terraform
        run: terraform init
        working-directory: ./terraform

      - name: Planificar Terraform
        run: terraform plan -var "image_repo_name=${{ env.DOCKER_IMAGE_NAME }}:${{ env.IMAGE_TAG }}"
        working-directory: ./terraform

      - name: Aplicar Terraform
        run: terraform apply -auto-approve -var "image_repo_name=${{ env.DOCKER_IMAGE_NAME }}:${{ env.IMAGE_TAG }}"
        working-directory: ./terraform

      - name: Obtener URL del Load Balancer
        run: |
          ALB_URL=$(terraform output -raw alb_dns_name)
          echo "La aplicación está disponible en: http://$ALB_URL"
        working-directory: ./terraform